
import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'id';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Nav
    'nav.assets': 'Assets',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.signup': 'Sign Up',
    'nav.login': 'Log In',
    'nav.creator_hub': 'Creator Hub',
    'nav.dashboard': 'My Dashboard',
    'nav.editor': 'Editor',
    'nav.search_placeholder': 'Search assets...',
    // Auth
    'auth.login_title': 'Welcome back',
    'auth.login_subtitle': 'Enter your details to access your account.',
    'auth.signup_title': 'Create an account',
    'auth.signup_subtitle': 'Start your creative journey with MODIVIS.',
    'auth.full_name': 'Full Name',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.remember_me': 'Remember for 30 days',
    'auth.forgot_password': 'Forgot password?',
    'auth.sign_in': 'Sign In',
    'auth.create_account': 'Create Account',
    'auth.continue_google': 'Continue with Google',
    'auth.dont_have_account': 'Don\'t have an account?',
    'auth.already_have_account': 'Already have an account?',
    'auth.terms': 'By signing up, you agree to our Terms and Privacy Policy.',
    // Landing
    'landing.hero_title_1': 'Discover Digital Assets &',
    'landing.hero_title_2': 'Edit with Ease',
    'landing.hero_desc': 'Your single source for high-quality digital assets and powerful online editing tools. Create, edit, and export in minutes.',
    'landing.search_placeholder_long': 'Search millions of photos, vectors, and videos...',
    'landing.search_btn': 'Search',
    'landing.trending': 'Trending:',
    'landing.try_editor': 'Try Our Editor',
    'landing.powerful_tools': 'Powerful Tools',
    'landing.editor_desc': 'Use the controls on the right to crop and rotate sample images. Experience the ease of editing directly in your browser with our AI-powered tools.',
    'landing.launch_editor': 'Launch Editor',
    'landing.crop': 'Crop',
    'landing.rotate': 'Rotate',
    'landing.trending_cats': 'Trending Categories',
    'landing.view_all': 'View All',
    'landing.explore': 'Explore',
    'landing.sell_work': 'Sell Your Work &',
    'landing.earn_royalties': 'Earn 70% Royalties',
    'landing.contributor_desc': 'Join our global community of contributors and earn from what you love. Share your best work with the world and get paid securely.',
    'landing.become_contributor': 'Become a Contributor',
    // Categories
    'cat.business': 'Business',
    'cat.nature': 'Nature',
    'cat.technology': 'Technology',
    'cat.medical': 'Medical',
    'cat.3d': '3D Renders',
    // Features Page
    'features.title': 'Everything You Need to Create',
    'features.subtitle': 'A complete ecosystem for digital creators, from discovery to editing and monetization.',
    'features.ai_editor': 'AI-Powered Editor',
    'features.ai_editor_desc': 'Edit images directly in your browser with advanced AI tools like background removal, upscaling, and magic eraser.',
    'features.marketplace': 'Global Marketplace',
    'features.marketplace_desc': 'Access millions of high-quality assets curated from top creators around the world.',
    'features.analytics': 'Advanced Analytics',
    'features.analytics_desc': 'Track your performance, sales, and audience engagement with detailed real-time dashboards.',
    'features.monetization': 'Creator Monetization',
    'features.monetization_desc': 'Earn competitive royalties (up to 70%) for your contributions with transparent payout systems.',
    'features.cta_title': 'Ready to get started?',
    'features.cta_btn': 'Join MODIVIS Today',
    // Footer
    'footer.legal': 'Legal',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.cookie': 'Cookie Policy',
    'footer.social': 'Social Media',
    'footer.newsletter': 'Newsletter',
    'footer.subscribe': 'Subscribe',
    'footer.enter_email': 'Enter your email',
    'footer.rights': '© 2024 MODIVIS. All rights reserved.',
    'footer.desc': 'High-quality digital assets and advanced online editing tools for creators worldwide.',
    // Marketplace
    'market.title': 'Digital Assets',
    'market.subtitle': 'Discover over 2 million curated assets.',
    'market.filter_type': 'Type',
    'market.filter_orientation': 'Orientation',
    'market.filter_color': 'Color',
    'market.filter_copyspace': 'Copy Space',
    'market.filter_license': 'License',
    'market.displaying': 'Displaying 120 assets',
    'market.edit': 'Edit',
    'market.premium': 'Premium',
    // Asset Detail
    'detail.home': 'Home',
    'detail.follow': 'Follow',
    'detail.following': 'Following',
    'detail.open_editor': 'Open in Editor',
    'detail.download': 'Download',
    'detail.save': 'Save',
    'detail.specs': 'Specifications',
    'detail.max_res': 'Max Resolution',
    'detail.license_type': 'License Type',
    'detail.file_type': 'File Type',
    'detail.upload_date': 'Upload Date',
    'detail.desc': 'Description',
    'detail.comments': 'Comments',
    'detail.related': 'Related Assets',
    'detail.pro_contributor': 'Pro Contributor',
    'detail.asset_desc_1': 'Discover the pinnacle of modern workspace design with this premium digital asset. Capturing a bright, airy office environment, this high-resolution image features minimalist furniture, abundant natural light from large windows, and subtle green accents from indoor plants. It\'s the perfect visual for corporate websites, architectural blogs, or any project that needs to convey professionalism, innovation, and a clean aesthetic.',
    'detail.asset_desc_2': 'This asset was rendered using high-end ray tracing techniques to ensure photorealistic lighting and textures. Perfect for background removal or direct use in marketing materials.',
    // Editor
    'editor.basic': 'Basic',
    'editor.premium_ai': 'Premium (AI)',
    'editor.crop_resize': 'Crop & Resize',
    'editor.adjustments': 'Adjustments',
    'editor.transform': 'Transform',
    'editor.ai_tools': 'AI Tools',
    'editor.remove_bg': 'Remove BG',
    'editor.magic_eraser': 'Magic Eraser',
    'editor.upscaler': 'Upscaler',
    'editor.filters': 'Filters',
    'editor.est_cost': 'Est. Cost',
    'editor.export': 'Export',
    'editor.brightness': 'Brightness',
    'editor.contrast': 'Contrast',
    'editor.saturation': 'Saturation',
    'editor.layers': 'Layers',
    // Export Modal
    'export.title': 'Export & Download',
    'export.subtitle': 'Complete payment to remove watermark.',
    'export.cost_breakdown': 'Cost Breakdown',
    'export.base_image': 'Base Image',
    'export.ai_adjustments': 'AI Adjustments',
    'export.total_cost': 'Total Cost',
    'export.payment_method': 'Payment Method',
    'export.use_token': 'Use Token Balance',
    'export.watch_ad': 'Watch Ad',
    'export.process_download': 'Process & Download',
    'export.watch_ad_desc': 'Watch a short video to cover cost.',
    'export.quota': 'Quota',
    'export.available': 'Available',
    // User Dashboard
    'user.dashboard': 'Dashboard',
    'user.my_assets': 'My Assets',
    'user.explore': 'Explore',
    'user.creator_mode': 'Creator Mode',
    'user.token_balance': 'Token Balance',
    'user.top_up': 'Top Up Tokens',
    'user.download_quota': 'Download Quota',
    'user.recent_projects': 'Recent Projects',
    'user.continue_editing': 'Continue Editing',
    'user.activity': 'Activity',
    // Creator Dashboard
    'creator.dashboard': 'Dashboard Kreator',
    'creator.marketplace': 'Pasar',
    'creator.upload_new': 'Unggah Aset Baru',
    'creator.total_downloads': 'Total Unduhan',
    'creator.total_views': 'Total Tayangan',
    'creator.revenue': 'Revenue (This Month)',
    'creator.performance': 'Performance Analytics',
    'creator.top_assets': 'Top Performing Assets',
    'creator.asset': 'Asset',
    'creator.date': 'Date',
    'creator.downloads': 'Downloads',
    'creator.revenue_table': 'Revenue',
    'creator.month_compare': 'vs last month',
    // Pricing
    'pricing.title': 'Hybrid Business Model for Growth',
    'pricing.subtitle': 'and Maximum Accessibility',
    'pricing.free_user': 'FREE USER',
    'pricing.pro_creator': 'PRO CREATOR',
    'pricing.ultra_business': 'ULTRA BUSINESS',
    'pricing.cost': 'Cost',
    'pricing.quota': 'Quota',
    'pricing.key_features': 'Key Features',
    'pricing.free_price': 'Rp 0',
    'pricing.pro_price': 'Rp 49.000/month',
    'pricing.ultra_price': 'Rp 99.000/month',
    'pricing.free_quota': '100 Tokens/month',
    'pricing.pro_quota': '350 Tokens/month',
    'pricing.ultra_quota': '500 Tokens/month',
    'pricing.feat_limited': 'Limited Access',
    'pricing.feat_ads': 'Must watch Reward Ads (1 Ad = 15 Tokens)',
    'pricing.feat_sd': 'SD Resolution',
    'pricing.feat_no_ads': 'Ad Free',
    'pricing.feat_hd': 'Full HD Resolution (1080p)',
    'pricing.feat_unlimited': 'Unlimited Download',
    'pricing.feat_rollover': 'Rollover Token (unused tokens accumulate)',
    'pricing.feat_4k': '4K/Original Resolution',
    'pricing.feat_priority': 'AI Server Priority',
    'pricing.choose_plan': 'Choose Plan',
    'pricing.current_plan': 'Current Plan',
    // Upload
    'upload.title': 'Upload New Asset',
    'upload.subtitle': 'Share your creation with the world',
    'upload.drag_drop': 'Drag and drop your files here',
    'upload.browse': 'or browse to upload',
    'upload.supported': 'Supported: JPG, PNG, OBJ, FBX (Max 50MB)',
    'upload.asset_details': 'Asset Details',
    'upload.asset_title': 'Asset Title',
    'upload.description': 'Description',
    'upload.category': 'Category',
    'upload.price': 'Price ($)',
    'upload.tags': 'Tags (comma separated)',
    'upload.publish': 'Publish Asset',
    'upload.cancel': 'Cancel',
    'upload.uploading': 'Uploading...',
    'upload.success': 'Asset published successfully!',
    // Payment
    'payment.title': 'Checkout',
    'payment.subtitle': 'Secure payment processing',
    'payment.method': 'Payment Method',
    'payment.card_holder': 'Card Holder Name',
    'payment.card_number': 'Card Number',
    'payment.expiry': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.pay_now': 'Pay Now',
    'payment.processing': 'Processing...',
    'payment.success_title': 'Payment Successful!',
    'payment.success_desc': 'Your subscription has been upgraded.',
    'payment.close': 'Close',
  },
  id: {
    // Nav
    'nav.assets': 'Aset',
    'nav.features': 'Fitur',
    'nav.pricing': 'Harga',
    'nav.signup': 'Daftar',
    'nav.login': 'Masuk',
    'nav.creator_hub': 'Pusat Kreator',
    'nav.dashboard': 'Dashboard Saya',
    'nav.editor': 'Editor',
    'nav.search_placeholder': 'Cari aset...',
    // Auth
    'auth.login_title': 'Selamat Datang Kembali',
    'auth.login_subtitle': 'Masukkan detail untuk mengakses akun Anda.',
    'auth.signup_title': 'Buat Akun',
    'auth.signup_subtitle': 'Mulai perjalanan kreatif Anda dengan MODIVIS.',
    'auth.full_name': 'Nama Lengkap',
    'auth.email': 'Alamat Email',
    'auth.password': 'Kata Sandi',
    'auth.remember_me': 'Ingat selama 30 hari',
    'auth.forgot_password': 'Lupa sandi?',
    'auth.sign_in': 'Masuk',
    'auth.create_account': 'Buat Akun',
    'auth.continue_google': 'Lanjut dengan Google',
    'auth.dont_have_account': 'Belum punya akun?',
    'auth.already_have_account': 'Sudah punya akun?',
    'auth.terms': 'Dengan mendaftar, Anda menyetujui Syarat dan Kebijakan Privasi kami.',
    // Landing
    'landing.hero_title_1': 'Temukan Aset Digital &',
    'landing.hero_title_2': 'Edit dengan Mudah',
    'landing.hero_desc': 'Sumber tunggal Anda untuk aset digital berkualitas tinggi dan alat pengeditan online yang canggih. Buat, edit, dan ekspor dalam hitungan menit.',
    'landing.search_placeholder_long': 'Cari jutaan foto, vektor, dan video...',
    'landing.search_btn': 'Cari',
    'landing.trending': 'Sedang Tren:',
    'landing.try_editor': 'Coba Editor Kami',
    'landing.powerful_tools': 'Alat Canggih',
    'landing.editor_desc': 'Gunakan kontrol di sebelah kanan untuk memotong dan memutar gambar sampel. Rasakan kemudahan mengedit langsung di browser Anda dengan alat AI kami.',
    'landing.launch_editor': 'Buka Editor',
    'landing.crop': 'Potong',
    'landing.rotate': 'Putar',
    'landing.trending_cats': 'Kategori Populer',
    'landing.view_all': 'Lihat Semua',
    'landing.explore': 'Jelajahi',
    'landing.sell_work': 'Jual Karyamu &',
    'landing.earn_royalties': 'Dapat 70% Royalti',
    'landing.contributor_desc': 'Bergabunglah dengan komunitas kontributor global kami dan dapatkan penghasilan dari apa yang Anda sukai. Bagikan karya terbaik Anda dengan dunia dan dibayar dengan aman.',
    'landing.become_contributor': 'Jadi Kontributor',
    // Categories
    'cat.business': 'Bisnis',
    'cat.nature': 'Alam',
    'cat.technology': 'Teknologi',
    'cat.medical': 'Medis',
    'cat.3d': 'Render 3D',
    // Features Page
    'features.title': 'Segala yang Anda Butuhkan untuk Berkarya',
    'features.subtitle': 'Ekosistem lengkap untuk kreator digital, dari penemuan aset hingga pengeditan dan monetisasi.',
    'features.ai_editor': 'Editor Bertenaga AI',
    'features.ai_editor_desc': 'Edit gambar langsung di browser Anda dengan alat AI canggih seperti penghapus latar, peningkat kualitas, dan penghapus ajaib.',
    'features.marketplace': 'Pasar Global',
    'features.marketplace_desc': 'Akses jutaan aset berkualitas tinggi yang dikurasi dari kreator top di seluruh dunia.',
    'features.analytics': 'Analitik Canggih',
    'features.analytics_desc': 'Lacak performa, penjualan, dan keterlibatan audiens Anda dengan dashboard real-time yang mendetail.',
    'features.monetization': 'Monetisasi Kreator',
    'features.monetization_desc': 'Dapatkan royalti kompetitif (hingga 70%) untuk kontribusi Anda dengan sistem pembayaran yang transparan.',
    'features.cta_title': 'Siap untuk memulai?',
    'features.cta_btn': 'Gabung MODIVIS Hari Ini',
    // Footer
    'footer.legal': 'Legal',
    'footer.terms': 'Syarat Layanan',
    'footer.privacy': 'Kebijakan Privasi',
    'footer.cookie': 'Kebijakan Cookie',
    'footer.social': 'Media Sosial',
    'footer.newsletter': 'Buletin',
    'footer.subscribe': 'Langganan',
    'footer.enter_email': 'Masukkan email Anda',
    'footer.rights': '© 2024 MODIVIS. Hak cipta dilindungi.',
    'footer.desc': 'Aset digital berkualitas tinggi dan alat pengeditan online yang canggih untuk kreator di seluruh dunia.',
    // Marketplace
    'market.title': 'Aset Digital',
    'market.subtitle': 'Temukan lebih dari 2 juta aset pilihan.',
    'market.filter_type': 'Tipe',
    'market.filter_orientation': 'Orientasi',
    'market.filter_color': 'Warna',
    'market.filter_copyspace': 'Ruang Kosong',
    'market.filter_license': 'Lisensi',
    'market.displaying': 'Menampilkan 120 aset',
    'market.edit': 'Edit',
    'market.premium': 'Premium',
    // Asset Detail
    'detail.home': 'Beranda',
    'detail.follow': 'Ikuti',
    'detail.following': 'Mengikuti',
    'detail.open_editor': 'Buka di Editor',
    'detail.download': 'Unduh',
    'detail.save': 'Simpan',
    'detail.specs': 'Spesifikasi',
    'detail.max_res': 'Resolusi Maksimal',
    'detail.license_type': 'Tipe Lisensi',
    'detail.file_type': 'Tipe File',
    'detail.upload_date': 'Tanggal Unggah',
    'detail.desc': 'Deskripsi',
    'detail.comments': 'Komentar',
    'detail.related': 'Aset Terkait',
    'detail.pro_contributor': 'Kontributor Pro',
    'detail.asset_desc_1': 'Temukan desain ruang kerja modern terbaik dengan aset digital premium ini. Menampilkan suasana kantor yang cerah dan lapang, gambar beresolusi tinggi ini menghadirkan furnitur minimalis, limpahan cahaya alami dari jendela besar, dan sentuhan hijau alami dari tanaman dalam ruangan. Visual yang sempurna untuk website perusahaan, blog arsitektur, atau proyek apa pun yang mengutamakan profesionalisme, inovasi, dan estetika yang bersih.',
    'detail.asset_desc_2': 'Aset ini dirender menggunakan teknik ray tracing canggih untuk memastikan pencahayaan dan tekstur yang fotorealistik. Sangat cocok untuk penghapusan latar belakang atau penggunaan langsung dalam materi pemasaran.',
    // Editor
    'editor.basic': 'Dasar',
    'editor.premium_ai': 'Premium (AI)',
    'editor.crop_resize': 'Potong & Ukuran',
    'editor.adjustments': 'Penyesuaian',
    'editor.transform': 'Transformasi',
    'editor.ai_tools': 'Alat AI',
    'editor.remove_bg': 'Hapus Latar',
    'editor.magic_eraser': 'Penghapus Ajaib',
    'editor.upscaler': 'Peningkat Kualitas',
    'editor.filters': 'Filter',
    'editor.est_cost': 'Est. Biaya',
    'editor.export': 'Ekspor',
    'editor.brightness': 'Kecerahan',
    'editor.contrast': 'Kontras',
    'editor.saturation': 'Saturasi',
    'editor.layers': 'Lapisan',
    // Export Modal
    'export.title': 'Ekspor & Unduh',
    'export.subtitle': 'Selesaikan pembayaran untuk menghapus watermark.',
    'export.cost_breakdown': 'Rincian Biaya',
    'export.base_image': 'Gambar Dasar',
    'export.ai_adjustments': 'Penyesuaian AI',
    'export.total_cost': 'Total Biaya',
    'export.payment_method': 'Metode Pembayaran',
    'export.use_token': 'Gunakan Saldo Token',
    'export.watch_ad': 'Tonton Iklan',
    'export.process_download': 'Proses & Unduh',
    'export.watch_ad_desc': 'Tonton video singkat untuk menutupi biaya.',
    'export.quota': 'Kuota',
    'export.available': 'Tersedia',
    // User Dashboard
    'user.dashboard': 'Dashboard',
    'user.my_assets': 'Aset Saya',
    'user.explore': 'Jelajahi',
    'user.creator_mode': 'Mode Kreator',
    'user.token_balance': 'Saldo Token',
    'user.top_up': 'Isi Ulang Token',
    'user.download_quota': 'Kuota Unduhan',
    'user.recent_projects': 'Proyek Terbaru',
    'user.continue_editing': 'Lanjutkan Edit',
    'user.activity': 'Aktivitas',
    // Creator Dashboard
    'creator.dashboard': 'Dashboard Kreator',
    'creator.marketplace': 'Pasar',
    'creator.upload_new': 'Unggah Aset Baru',
    'creator.total_downloads': 'Total Unduhan',
    'creator.total_views': 'Total Tayangan',
    'creator.revenue': 'Pendapatan (Bulan Ini)',
    'creator.performance': 'Analisis Performa',
    'creator.top_assets': 'Aset Performa Terbaik',
    'creator.asset': 'Aset',
    'creator.date': 'Tanggal',
    'creator.downloads': 'Unduhan',
    'creator.revenue_table': 'Pendapatan',
    'creator.month_compare': 'vs bulan lalu',
    // Pricing
    'pricing.title': 'Model Bisnis Hybrid untuk Pertumbuhan',
    'pricing.subtitle': 'dan Aksesibilitas Maksimal',
    'pricing.free_user': 'FREE USER',
    'pricing.pro_creator': 'PRO CREATOR',
    'pricing.ultra_business': 'ULTRA BUSINESS',
    'pricing.cost': 'Biaya',
    'pricing.quota': 'Kuota',
    'pricing.key_features': 'Fitur Kunci',
    'pricing.free_price': 'Rp 0',
    'pricing.pro_price': 'Rp 49.000/bulan',
    'pricing.ultra_price': 'Rp 99.000/bulan',
    'pricing.free_quota': '100 Token/bulan',
    'pricing.pro_quota': '350 Token/bulan',
    'pricing.ultra_quota': '500 Token/bulan',
    'pricing.feat_limited': 'Akses terbatas',
    'pricing.feat_ads': 'Wajib menonton Video Reward Ads (1 Iklan = 15 Token)',
    'pricing.feat_sd': 'Resolusi SD',
    'pricing.feat_no_ads': 'Bebas Iklan',
    'pricing.feat_hd': 'Resolusi Full HD (1080p)',
    'pricing.feat_unlimited': 'Unlimited Download',
    'pricing.feat_rollover': 'Rollover Token (sisa token diakumulasi)',
    'pricing.feat_4k': 'Resolusi 4K/Original',
    'pricing.feat_priority': 'Prioritas server AI',
    'pricing.choose_plan': 'Pilih Paket',
    'pricing.current_plan': 'Paket Saat Ini',
    // Upload
    'upload.title': 'Unggah Aset Baru',
    'upload.subtitle': 'Bagikan kreasi Anda dengan dunia',
    'upload.drag_drop': 'Seret dan lepas file Anda di sini',
    'upload.browse': 'atau jelajahi untuk mengunggah',
    'upload.supported': 'Didukung: JPG, PNG, OBJ, FBX (Maks 50MB)',
    'upload.asset_details': 'Detail Aset',
    'upload.asset_title': 'Judul Aset',
    'upload.description': 'Deskripsi',
    'upload.category': 'Kategori',
    'upload.price': 'Harga ($)',
    'upload.tags': 'Tag (pisahkan dengan koma)',
    'upload.publish': 'Terbitkan Aset',
    'upload.cancel': 'Batal',
    'upload.uploading': 'Mengunggah...',
    'upload.success': 'Aset berhasil diterbitkan!',
    // Payment
    'payment.title': 'Checkout',
    'payment.subtitle': 'Pemrosesan pembayaran aman',
    'payment.method': 'Metode Pembayaran',
    'payment.card_holder': 'Nama Pemegang Kartu',
    'payment.card_number': 'Nomor Kartu',
    'payment.expiry': 'Tanggal Kadaluarsa',
    'payment.cvv': 'CVV',
    'payment.pay_now': 'Bayar Sekarang',
    'payment.processing': 'Memproses...',
    'payment.success_title': 'Pembayaran Berhasil!',
    'payment.success_desc': 'Langganan Anda telah ditingkatkan.',
    'payment.close': 'Tutup',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
